#!/usr/bin/env python3
import sys
import numpy as np
from scipy.stats import kurtosis, skew
data = np.array([float(line.strip()) for line in sys.stdin])
min_val = np.min(data)
fib_23_6 = np.percentile(data, 23.6)
q1 = np.percentile(data, 25)
fib_38_2 = np.percentile(data, 38.2)
median_val = np.median(data)
mean_val = np.mean(data)
harmonic_mean_val = data / np.sum(1.0/data)
fib_61_8 = np.percentile(data, 61.8)
q3 = np.percentile(data, 75)
fib_78_6 = np.percentile(data, 78.6)
max_val = np.max(data)
std_dev = np.std(data)
kurtosis_val = kurtosis(data)
skew_val = skew(data)
avg_dev = np.mean(np.abs(data - mean_val))
print(f"Min: {min_val}")
print(f"23.6% Fibonacci: {fib_23_6}")
print(f"1st Quartile: {q1}")
print(f"38.2% Fibonacci: {fib_38_2}")
print(f"Median: {median_val}")
print(f"Mean: {mean_val}")
print(f"HarmonicMean: {harmonic_mean_val}")
print(f"61.8% Fibonacci: {fib_61_8}")
print(f"3rd Quartile: {q3}")
print(f"78.6% Fibonacci: {fib_78_6}")
print(f"Max: {max_val}")
print(f"Standard Deviation: {std_dev}")
print(f"Kurtosis: {kurtosis_val}")
print(f"Skew: {skew_val}")
print(f"Average Deviation: {avg_dev}")
