#!/usr/bin/env python3
import yaml
import os,sys
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import numpy as np
import pandas as pd
import yfinance as yf
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
tf.get_logger().setLevel('ERROR')

def create_dataset(dataset, time_step=100):
 X, Y = [], []
 for i in range(len(dataset) - time_step - 1):
   a = dataset[i:(i + time_step), 0] # Extracting 'time_step' number of elements
   X.append(a)
   Y.append(dataset[i + time_step, 0]) # The next element
 return np.array(X), np.array(Y)

def predict_next_days(model, last_data, scaler, n_days, time_step):
 future_predictions = last_data[-time_step:].tolist()
 for _ in range(n_days):
   x_input = np.array(future_predictions[-time_step:]).reshape(1, -1, 1)
   next_day_pred = model.predict(x_input)
   future_predictions.append([next_day_pred[0][0]])
   future_predictions_scaled = np.array(future_predictions[-n_days:]).reshape(-1, 1)
   future_predictions = scaler.inverse_transform(future_predictions_scaled)
   return future_predictions.flatten()

stocks = ['SMR','UEC','DNN','IVR','PHO','URG','NXE','KTOS','CDE','LEU','KURA']
time_step = 100
future_days = 1 

for ticker in stocks:
  print(ticker)
  data = yf.download(ticker, start=None, end=None, rounding=False, period="max", progress=False)
  if data.empty:
    print(f"No data fetched for {ticker}. Skipping.")
    continue
  data = data[['Close']].copy()
  last = data.iloc[-1]
  print(last.to_string())
  data.ffill(inplace=True)
  scaler = MinMaxScaler(feature_range=(0, 1))
  scaled_data = scaler.fit_transform(data)
  train_data, test_data = scaled_data[0:int(len(scaled_data)*0.7)], scaled_data[int(len(scaled_data)*0.7):]
  X_train, y_train = create_dataset(train_data, time_step)
  X_test, y_test = create_dataset(test_data, time_step)
  X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
  X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)
  model = Sequential()
  model.add(LSTM(50, return_sequences=True, input_shape=(time_step, 1)))
  model.add(LSTM(50, return_sequences=False))
  model.add(Dense(1))
  model.compile(optimizer='adam', loss='mean_squared_error')
  model.fit(X_train, y_train, batch_size=64, epochs=10000, verbose=0)
  predictions = model.predict(X_test)
  predictions = scaler.inverse_transform(predictions)
  future_pred = predict_next_days(model, scaled_data, scaler, future_days, time_step)
  print(future_pred)
 
